services:
  - type: web
    name: car-stock-checker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7770662830:AAF81ZmkPNNCxV2sUg-0jSVyEb64fTNkBn8
      - key: TELEGRAM_CHAT_ID
        value: 1476078120
      - key: CAR_URL
        value: https://www.tesla.com/tr_TR/inventory/new/my?arrangeby=plh&zip=34025&range=0
