services:
  - type: web
    name: tesla-stock-tracker
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromGitHub:
          repo: your-github-username/your-repo-name
          secret: TELEGRAM_BOT_TOKEN
      - key: TELEGRAM_CHAT_ID
        fromGitHub:
          repo: your-github-username/your-repo-name
          secret: TELEGRAM_CHAT_ID
      - key: UPTIMEROBOT_PING_URL
        value: "https://dashboard.uptimerobot.com/monitors/800478109"  # UptimeRobot API URL'nizi buraya ekleyin
