services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: FLASK_APP
        value: "main.py"
      - key: FLASK_ENV
        value: "production"
