services:
  - type: web
    name: tesla-stock-tracker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python tesla_stock_tracker.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromGitHub:
          repo: your-github-username/your-repo-name
          secret: TELEGRAM_BOT_TOKEN
      - key: TELEGRAM_CHAT_ID
        fromGitHub:
          repo: your-github-username/your-repo-name
          secret: TELEGRAM_CHAT_ID
      - key: CHECK_INTERVAL_SECONDS
        value: 1
